
<CustomButton@Button>
    text: self.text
    markup: True
    font_size: 40
    size_hint: (None, None)
    size: (70, 70)
    background_color: (0, 0, 0, 0)
    color: self.color
    on_press: self.on_press
    fondo_color: (0,0,0,0)
    canvas.before:
        Color:
            rgba: root.fondo_color
        RoundedRectangle:
            size: self.size
            pos: self.pos
            radius:  [35,]
<Ui>:
    id: val
    orientation: 'vertical'
    spacing: dp(12)
    padding: [dp(12),dp(12),dp(12),dp(12)]

    BoxLayout:
        pantalla: entry
        size_hint: 1, 0.25
        spacing: dp(12)
        TextInput:
            id: entry
            halign: 'right'
            font_size: 50
            foreground_color: val.white
            cursor_color: val.white
            background_color: val.black
    GridLayout:
        size_hint: 1,0.60
        cols: 4
        spacing: dp(12)
        CustomButton:
            text: 'AC'
            on_press: app.borrar_uno(entry.text)
            fondo_color: val.gray
            color: val.black
        CustomButton:
            text: '+/-'
            on_press: app.mas_menos(entry.text)
            fondo_color: val.gray
            color: val.black
        CustomButton:
            text: '%'
            on_press: app.porcentaje(entry.text)
            fondo_color: val.gray
            color: val.black
        CustomButton:
            text: '÷'
            on_press: entry.text += '/'
            fondo_color: val.orange
            color: val.white
#####
        CustomButton:
            text: '7'
            on_press: entry.text += self.text
            fondo_color: val.gray_black
            color: val.white
        CustomButton:
            text: '8'
            on_press: entry.text += self.text
            fondo_color: val.gray_black
            color: val.white
        CustomButton:
            text: '9'
            on_press: entry.text += self.text
            fondo_color: val.gray_black
            color: val.white
        CustomButton:
            text: 'x'
            on_press: entry.text += '*'
            fondo_color: val.orange
            color: val.white
#####
        CustomButton:
            text: '4'
            on_press: entry.text += self.text
            fondo_color: val.gray_black
            color: val.white
        CustomButton:
            text: '5'
            on_press: entry.text += self.text
            fondo_color: val.gray_black
            color: val.white
        CustomButton:
            text: '6'
            on_press: entry.text += self.text
            fondo_color: val.gray_black
            color: val.white
        CustomButton:
            text: '-'
            on_press: entry.text += self.text
            fondo_color: val.orange
            color: val.white
#####
        CustomButton:
            text: '1'
            on_press: entry.text += self.text
            fondo_color: val.gray_black
            color: val.white
        CustomButton:
            text: '2'
            on_press: entry.text += self.text
            fondo_color: val.gray_black
            color: val.white
        CustomButton:
            text: '3'
            on_press: entry.text += self.text
            fondo_color: val.gray_black
            color: val.white
        CustomButton:
            text: '+'
            on_press: entry.text += self.text
            fondo_color: val.orange
            color: val.white
###
    GridLayout:
        size_hint: 1,0.15
        spacing: dp(12)
        cols: 3
        CustomButton:
            text: '0'
            on_press: entry.text += self.text
            fondo_color: val.gray_black
            color: val.white
            size: (152, 70)
        CustomButton:
            text: '.'
            on_press: entry.text += self.text
            fondo_color: val.gray_black
            color: val.white
        CustomButton:
            text: '='
            on_press: app.operacion(entry.text)
            fondo_color: val.orange
            color: val.white
